"""add_person_dates_table

Revision ID: 695e87e83d83
Revises: 
Create Date: 2026-03-09 09:31:05.510545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695e87e83d83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_dates_id'), 'person_dates', ['id'], unique=False)
    op.create_index(op.f('ix_person_dates_person_id'), 'person_dates', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_dates_person_id'), table_name='person_dates')
    op.drop_index(op.f('ix_person_dates_id'), table_name='person_dates')
    op.drop_table('person_dates')
    # ### end Alembic commands ###
